[web]
graceful = true
connect_info = true

[web.middlewares]
static = { enable = true, uri = "/", path = "frontend/build" }

[web.openapi]
doc_prefix = "/openapi/docs"
info = { title = "autowds api document", version = "0.0.1" }

[mail]
host = "smtp.163.com"                                                      # SMTP mail server address,
port = 465                                                                 # SMTP server port number
secure = true                                                              # Response timeout, in milliseconds
auth = { user = "hff1996723@163.com", password = "${MAIL_AUTH_PASSWORD}" } # Authentication information

[email]
from = "hff1996723@163.com"

[sea-orm]
uri = "${DATABASE_URL:postgres://postgres:xudjf23adj213@localhost:5432/autowds}"

[sea-orm-web]
one_indexed = true

[redis]
uri = "${REDIS_URL:redis://localhost}"

[pay]
## https://openhome.alipay.com/develop/sandbox/app
test_pay_amount = ${TEST_PAY_AMOUNT:false}
wechat_pay_enable = true # 微信配置全为环境变量
alipay_enable = true
alipay_api_url = "${ALIPAY_API_URL:https://openapi-sandbox.dl.alipaydev.com/gateway.do}"
alipay_app_id = "${ALIPAY_APP_ID:2021000149633962}"
alipay_root_cert_sn = "${ALIPAY_ROOT_CERT_SN}"
alipay_public_key = "${ALIPAY_PUBLIC_KEY}"
alipay_app_cert_sn = "${ALIPAY_APP_CERT_SN}"
alipay_app_private_key = "${ALIPAY_APP_PRIVATE_KEY}"
alipay_app_public_key = "${ALIPAY_APP_PUBLIC_KEY}"
alipay_callback_url = "${ALIPAY_CALLBACK_URL:https://p.dtiku.cn/pay/alipay/callback}"